# splat configuration for Fate/Unlimited Codes (Japan) SLPM_551.08 — written by gen_splat_yaml.py 2026-09-08T05:20:13Z
name: fate-unlimited-codes-jp
sha1: 825b867ecf30b761b8261a528e86101aa4bc03ca
options:
  basename: SLPM_551.08
  target_path: disc/SLPM_551.08
  base_path: ..
  platform: ps2
  compiler: MWCCPS2
  asm_path: asm
  src_path: src
  build_path: build
  ld_script_path: build/SLPM_551.08.ld
  symbol_addrs_path: config/symbol_addrs.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/undefined_syms_auto.txt
  find_file_boundaries: false
  migrate_rodata_to_functions: false
  asm_function_macro: glabel
  asm_data_macro: dlabel
  asm_jtbl_label_macro: jlabel
  asm_inc_header: ".set noat      /* allow manual use of $at */\n.set noreorder /* don't insert nops after branches */\n\n"
  section_order: [".text", ".data", ".rodata", ".bss"]
  generated_c_preamble: "#include \"common.h\""
  generated_s_preamble: ""
  string_encoding: SHIFT-JIS
  data_string_encoding: SHIFT-JIS
  rodata_string_guesser_level: 0
  data_string_guesser_level: 0
  asm_emit_size_directive: false
  gp_value: 0x00510470
segments:
  - name: main
    type: code
    start: 0x00000080
    vram: 0x00100000
    bss_size: 0x0002D180
    subalign: 16
    subsegments:
      - [0x00000080, asm, crt0]
      - [0x000002B0, asm, sdk_dma_graph]
      - [0x00003FE0, asm, sdk_kernel]
      - [0x00007880, asm, sdk_stdio]
      - [0x0000C240, asm, sdk_loadfile]
      - [0x0000E100, asm, sdk_mc]
      - [0x000117C0, asm, sdk_ipu]
      - [0x0001B4F0, asm, sdk_pad_scf]
      - [0x0001E2E0, asm, libc]
      - [0x0002E0C0, asm, libm]
      - [0x000330D0, asm, cri_adx]
      - [0x000580B0, asm, game_00]
      - [0x00076720, c, game_00/func_001766A0]
      - [0x000767C0, c, game_00/func_00176740]
      - [0x00076830, asm, game_00_1]
      - [0x00076C40, c, game_00/func_00176BC0]
      - [0x00076C54, asm, game_00_2]
      - [0x00076C60, c, game_00/func_00176BE0]
      - [0x00076C80, c, game_00/func_00176C00]
      - [0x00076C90, c, game_00/func_00176C10]
      - [0x00076CA4, asm, game_00_3]
      - [0x00076CB0, c, game_00/func_00176C30]
      - [0x00076CCC, asm, game_00_4]
      - [0x00076CD0, c, game_00/func_00176C50]
      - [0x00076CE0, asm, game_00_5]
      - [0x00077620, c, game_00/func_001775A0]
      - [0x00077698, asm, game_00_6]
      - [0x000780E0, c, game_00/func_00178060]
      - [0x000780F4, asm, game_00_7]
      - [0x00099130, c, game_00/func_001990B0]
      - [0x00099138, asm, game_00_8]
      - [0x00099D70, c, game_00/func_00199CF0]
      - [0x00099D7C, asm, game_00_9]
      - [0x000A3850, c, game_00/func_001A37D0]
      - [0x000A3878, asm, game_00_10]
      - [0x000A3880, c, game_00/func_001A3800]
      - [0x000A38A0, c, game_00/func_001A3820]
      - [0x000A38C0, asm, game_00_11]
      - [0x000A3B00, c, game_00/func_001A3A80]
      - [0x000A3B10, asm, game_00_12]
      - [0x000A3EB0, c, game_00/func_001A3E30]
      - [0x000A3F1C, asm, game_00_13]
      - [0x000A3F20, c, game_00/func_001A3EA0]
      - [0x000A3F94, asm, game_00_14]
      - [0x000A4820, c, game_00/func_001A47A0]
      - [0x000A4848, asm, game_00_15]
      - [0x000A4A20, c, game_00/func_001A49A0]
      - [0x000A4A54, asm, game_00_16]
      - [0x000A54D0, c, game_00/func_001A5450]
      - [0x000A553C, asm, game_00_17]
      - [0x001A6040, asm, game_render]
      - [0x001E60C0, asm, game_01]
      - [0x00253730, asm, sdk_cdvd]
      - [0x00254070, asm, game_02]
      - [0x0026EBB0, asm, game_model]
      - [0x00284600, data, data_00]
      - [0x002B0080, data, data_sdk]
      - [0x002D3080, data, data_01]
      - [0x003E2080, rodata, rodata_str]
      - [0x00409180, bss, main_bss]
  - [0x00409180]
